services:
  db:
    image: mysql:8.0
    container_name: unitedintalkblog_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - unitedintalkblog_db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: unitedintalkblog_app
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
    volumes:
      - unitedintalkblog_wp_data:/var/www/html

volumes:
  unitedintalkblog_db_data:
  unitedintalkblog_wp_data: